links:
  rails_tutorial:
    home_page: "https://www.railstutorial.org/"
    help_page: "https://www.railstutorial.org/help"
    about_page: "https://rubyonrails.org/"
    book_page: "https://www.railstutorial.org/book"
    learnenough: "https://www.learnenough.com/"
    screencast: "https://screencasts.railstutorial.org/"
  gravartar: "https://secure.gravatar.com/avatar/"
  gravartar_change: "https://gravatar.com/emails"

validations:
  name:
    max_length: 50
  email:
    max_length: 255
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  password:
    min_length: 6

gravartar:
  size_default: 80
  size_list: 50

params:
  one: 1
